travis:
  secure:
    BINSTAR_TOKEN: qw90YtDKMy/9tcb/bIbtw8ryfHDZi0oVz1ZTj+VSFim6pFOq7vIMl+vM6S3utEoiylkR1/KsqYdTM12fq+GfflpClZQ7tFlrV1PDNyj+t0qgnWohRcZD/uqsxTIwrP2orN9id/P1kySxnu4NGiXjM1NFtHExR2EtUCTUt4jCFr9ZfLY7UdIz4SDm/t85hBeEXCok61aftllZ2QAvPUr4lQXQgAGLv79aumsOcMHSQjb6bIXey/RBunTPBRXQxiG9047o4iDS6YHtw64Wqyong49Cr4uRXtyWTLuj1KDTAWdLJLD0jr99TDlS3VGqq95dcLVc1AaGdhHMV2C0QDfzm5IXzE5Dog6cCgK2MfVW7FioVyQIRJMTPJt7mI6RNCCOHSuPrUXpzF2Oq/RjyqICES1ouZqIK7L6YRXlXH0q0ofA75TtR2ctBsKhxPUy5qXKDwfyWoc3+Tz7RxW65iAyAjmwJ/epp4+ssLnnyJ3IaOCDFM5ST3bbASmaDaewnFkp94hriPXZfc+QlsXlQ8OCTaKSZoZMuVQlq5Fs3I1ZCQuFqfNfNBcUq5Lk2PYQALsu+YAVfG2+VWe/FnBIYXfyIOF/dvh+3bhbYd47P5c1qZ+8bbPztcy6H3bUhaw1bRcS7TdJbkRpHDM4oz1q7kht/uAP0vwSztlRENAtQPEKEB4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
