travis:
  secure:
    BINSTAR_TOKEN: P6RVhwb5FoIEJ01YC3HDEE4lXYxMTDIz9dnWT16te1zzTzYXyP7o3B1yzv4fLR+PF6YkgPaRUyrXu9f0T/TfUp87v423JWxvAo8c118xxuBpG8ou1RPqGakt4IZahTpO2qRDl41qijbwOH2g23uWWhQ0TvRd0csSGbvLYu+3RLleOkVRAlfpfZtJoS4C7MQmFhhthaDe/t5PwqfX8dBX3vPdijh+nuUy1obYp0++W4hlpIzL5ZmOUsxupDIVj1DZVneawKFpfMfpCHBN6Du0Vm1Xqr/00lOcKCcMYZpmNVUHmAP3hLZNLd1qonjIYd3vouDnAbJZEx89paYwUcecsGCm8tH16BQxcdChZD2IetyI04eLmChKIcqZSTvMn+KIEo8729oPdu11kIvZVzWu1sOvQavY6THPjbCuMqqE0sTBznA7kqe4uYJKqt9Jgi/KM4rcPUDzcjiOOOTg8SQWIHFfQIGVZDdKdGeMR9+vTlRIROvy8UojixhxAVzjnYELAwI1cce85xQ4b9zfHHbjYTMCFBtkd+CKNmv8oOwkVRpkjZeg9tTL74DiEuFBnrqNWSewMAU7mjslb42qMySKhsxNoS6YL0ZFZKkr9RDYQfMBJq7ypYwTpov9rxqqOyH7JriHDQmjHUy0iqfqkLLd/yTlplN0OpKHyuEoa/k2RfE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
